### ISSUE TITLE
New Zealand display support

### ISSUE THREAD

**Issue by nvonahsen** [spencermountain/timezone-soft#3]
Hey, been trying to use this on project where NZ is one of our major zones.
I noticed that the display function seems to return undefined for both the daylight and standard codes on the Pacific/Auckland timezone. Would expect these to be NZDT and NZST respectively.

Wondering if this will be supported in the near future?

Cheers and thanks for the library

**Comment by spencermountain** [comment]
good catch. fixed in `0.2.0`
cheers

**Comment by nvonahsen** [comment]
Just updated to 0.2.0 and still getting the issue

```javascript
import stInformalTz from 'spacetime-informal';
const tzCodes = stInformalTz.display('Pacific/Auckland')
console.log(tzCodes)
```

Gives: {iana: "Pacific/Auckland", standard: undefined, daylight: undefined}

In a quick skim of the library code i saw commented out
![image](https://user-images.githubusercontent.com/16808913/80574343-c3336500-8a55-11ea-9d0c-0d6626b0ff09.png)
in 05-metazones.js, maybe related?

**Comment by spencermountain** [comment]
thanks, i'll take a look at this next week.

**Comment by spencermountain** [comment]
this should be fixed now in `0.3.0`
thanks
